---
title: "R Notebook"
output: html_notebook
---

# TITLE

## Librarys
```{r Librarys}
install.packages("tidyverse")
```


```{r}
library(ggplot2)
```

## Getting data
```{r}
dir <- "Fitabase Data 4.12.16-5.12.16"

daily_activity <- read.csv(file.path(dir, "dailyActivity_merged.csv"))
daily_calories <- read.csv(file.path(dir, "dailyCalories_merged.csv"))
daily_intensities <- read.csv(file.path(dir, "dailyIntensities_merged.csv"))
daily_steps <- read.csv(file.path(dir, "dailySteps_merged.csv"))

colnames(daily_activity)
colnames(daily_calories)
colnames(daily_intensities)
colnames(daily_steps)
```
```{r}
sleep <- read.csv(file.path(dir, "sleepDay_merged.csv"))
weight <- read.csv(file.path(dir, "weightLogInfo_merged.csv"))
steps_narrow <- read.csv(file.path(dir, "minuteStepsNarrow_merged.csv"))
steps_wide <- read.csv(file.path(dir, "minuteStepsWide_merged.csv"))

heart_rate <- read.csv(file.path(dir, "heartrate_seconds_merged.csv"))
hourly_calories <- read.csv(file.path(dir, "hourlyCalories_merged.csv"))
minutes_calories_narrow <- read.csv(file.path(dir, "minuteCaloriesNarrow_merged.csv"))


View(sleep)
```


## Data cleaning

```{r}
summary(daily_activity)
```
```{r}
boxplot_daily_activity <- boxplot(subset(daily_activity, select = -c(ActivityDate, Id, TotalSteps, Calories, SedentaryMinutes)), xaxt="n",xlab="", size = 50)



par(cex.lab=10.5) # is for y-axis

par(cex.axis=20.5) # is for x-axis

tick <- seq_along(boxplot_daily_activity$names)
axis(1, at = tick, labels = FALSE)
text(tick, par("usr")[3] - 0.3, boxplot_daily_activity$names, srt = 90, xpd = TRUE)

```


## Plots
```{r}
ggplot(daily_activity, mapping = aes(x = TotalSteps, y = Calories)) + geom_point() + geom_smooth()
```
```{r}
ggplot(daily_activity, mapping = aes(x = SedentaryMinutes, y = Calories)) + geom_point() + geom_smooth()
```

```{r}
ggplot(daily_activity, mapping = aes(x = TotalDistance, y = Calories)) + geom_point() + geom_smooth()
```
```{r}
# Melt the data frame to long format
library(reshape2)
melted_data <- melt(daily_activity, id.vars = c("ActivityDate", "Id", "TotalSteps", "Calories", "SedentaryMinutes"), 
                    measure.vars = c("VeryActiveMinutes", "FairlyActiveMinutes", "LightlyActiveMinutes", "SedentaryMinutes"))

# Plotting using ggplot2
ggplot(melted_data, aes(x = variable, y = value, fill = variable)) +
  geom_bar(stat = "identity") +
  facet_wrap(~variable, scales = "free_y") +  # Separate plots for each activity type
  labs(x = "Activity Type", y = "Minutes", fill = "Activity Type") +
  theme_minimal()
```
```{r}
ggplot(heart_rate, mapping = aes(x = Time, y = Value)) + geom_line()
```

